version: "3.4"

services:
  web:
    build:
      context: .
      args:
        - RAILS_MASTER_KEY=$RAILS_MASTER_KEY
        - TENANT_MASTER_KEY=$TENANT_MASTER_KEY
        - RAILS_ENV=$RAILS_ENV
    environment:
      DB_HOST: db
      REDIS_URL: redis://redis:6379
    ports:
      - "80:3000"
    depends_on:
      - db
      - redis
      - sidekiq
    volumes:
      - .:/app
      - ./vendor/bundle:/app/vendor/bundle
      - ./.bundle:/app/.bundle
      - ./node_modules:/app/node_modules
  redis:
    image: "redis:alpine"
  db:
    image: "postgres:11.1"
    environment:
      POSTGRES_USER: nokul
      POSTGRES_PASSWORD: nokul
  sidekiq:
    build:
      context: .
      args:
        - RAILS_MASTER_KEY=$RAILS_MASTER_KEY
        - TENANT_MASTER_KEY=$TENANT_MASTER_KEY
        - RAILS_ENV=$RAILS_ENV
    environment:
      DB_HOST: db
      REDIS_URL: redis://redis:6379
    command: sh -c "bundle exec sidekiq -q high -q low"
    depends_on:
      - db
      - redis
  test:
    build:
      context: .
      args:
        - RAILS_MASTER_KEY=$RAILS_MASTER_KEY
        - TENANT_MASTER_KEY=$TENANT_MASTER_KEY
        - RAILS_ENV=$RAILS_ENV
        - NODE_ENV=$NODE_ENV
    environment:
      DB_HOST: db
      REDIS_URL: redis://redis:6379
      RAILS_MASTER_KEY: $RAILS_MASTER_KEY
      CODACY_PROJECT_TOKEN: $CODACY_PROJECT_TOKEN
      RAILS_ENV: $RAILS_ENV
      NODE_ENV: $NODE_ENV
      CI: $CI
    depends_on:
      - db
      - redis
    volumes:
      - $HOME/bundle:/app/vendor/bundle
      - $HOME/.bundle_config:/app/.bundle
      - $HOME/node_modules:/app/node_modules
